
[Interface]
PrivateKey = 8LXZXD0SEiGHZNH204FQ5Ic00pNvfStpkjYAeP03NSY=
Address = fdaa:2d:cd98:a7b:15:0:a:202/120
DNS = fdaa:2d:cd98::3

[Peer]
PublicKey = Ke1ggzAYxdOZIJX9xxbZe67/oau+EUlLA4fkb4e6wH4=
AllowedIPs = fdaa:2d:cd98::/48
Endpoint = qro1.gateway.6pn.dev:51820
PersistentKeepalive = 15

