
[Interface]
PrivateKey = JasvJ+hsBfgAdbfjS0cNDqb3otxYtMtCZmmNjPsjmFc=
Address = fdaa:29:bf7:a7b:15:0:a:502/120
DNS = fdaa:29:bf7::3

[Peer]
PublicKey = Ke1ggzAYxdOZIJX9xxbZe67/oau+EUlLA4fkb4e6wH4=
AllowedIPs = fdaa:29:bf7::/48
Endpoint = qro1.gateway.6pn.dev:51820
PersistentKeepalive = 15

