# fly.toml app configuration file generated for frontend-morning-haze-4592 on 2025-10-24T10:02:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'geoportalbeta'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
