# fly.toml app configuration file generated for geoportalbetav2 on 2025-12-24T09:04:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'geoportalbetav2'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 16
  memory_mb = 32768
