# fly.toml app configuration file generated for backend-solitary-fire-911 on 2025-12-24T10:04:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-solitary-fire-911'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb' 
  cpu_kind = 'performance'
  cpus = 8  