# fly.toml app configuration file generated for backendgeoportal on 2026-01-21T10:43:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'geoportal-backend-1'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 8
  memory_mb = 16384
