# fly.toml app configuration file generated for backend-weathered-silence-5682 on 2025-10-24T09:47:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-blue-shape-6900'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 16
